/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kamis;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormMasyarakat extends javax.swing.JFrame {

    public Statement st;
    Connection cn = akbar.Koneksi.Koneksi();
    
    public FormMasyarakat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMasNik = new javax.swing.JTextField();
        txtMasNama = new javax.swing.JTextField();
        cbJv = new javax.swing.JComboBox<>();
        cbJenis = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAl = new javax.swing.JTextArea();
        btnMasBatal = new javax.swing.JButton();
        btnMasSave = new javax.swing.JButton();
        btnMasLog = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Daftar Vaksin");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NIK");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 98, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jenis Vaksin");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 136, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Jenis Kelamin");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 174, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Alamat");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 209, -1, -1));
        jPanel1.add(txtMasNik, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 57, 219, -1));
        jPanel1.add(txtMasNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 95, 219, -1));

        cbJv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sinovac", "Moderna", "Pfizer", "Sinopharm", "AstraZeneca" }));
        jPanel1.add(cbJv, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 133, 219, -1));

        cbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki Laki", "Perempuan" }));
        jPanel1.add(cbJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 171, 219, -1));

        txtAl.setColumns(20);
        txtAl.setRows(5);
        jScrollPane1.setViewportView(txtAl);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 209, 219, -1));

        btnMasBatal.setBackground(new java.awt.Color(255, 255, 102));
        btnMasBatal.setText("Batal");
        btnMasBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasBatalActionPerformed(evt);
            }
        });
        jPanel1.add(btnMasBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 324, -1, -1));

        btnMasSave.setBackground(new java.awt.Color(51, 255, 51));
        btnMasSave.setText("Save");
        btnMasSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnMasSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 323, -1, -1));

        btnMasLog.setBackground(new java.awt.Color(255, 0, 0));
        btnMasLog.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnMasLog.setText("Logout");
        btnMasLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasLogActionPerformed(evt);
            }
        });
        jPanel1.add(btnMasLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 323, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\SISWA\\Downloads\\doctor-holding-syringe-with-vaccine-patient.jpg")); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-730, -250, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMasSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasSaveActionPerformed
        try{
            st = cn.createStatement();
            st.executeUpdate("INSERT INTO siswa VALUES('" +txtMasNik.getText() + "','"
            +txtMasNama.getText() +"','"
            +cbJv.getSelectedItem() +"','"
            +cbJenis.getSelectedItem()+"','"
            +txtAl.getText()+ "')");
            JOptionPane.showMessageDialog(null, "Simpan Berhasil");
            
        }catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnMasSaveActionPerformed

    private void btnMasLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasLogActionPerformed
        FormLogin fl = new FormLogin();
                        fl.show();
                    this.dispose();
    }//GEN-LAST:event_btnMasLogActionPerformed

    private void btnMasBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasBatalActionPerformed
        reset();
    }//GEN-LAST:event_btnMasBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMasyarakat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMasyarakat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMasyarakat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMasyarakat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMasyarakat().setVisible(true);
            }
        });
    }
    public void reset(){
        txtMasNik.setText("");
        txtMasNama.setText("");
        cbJv.setSelectedItem("");
        cbJenis.setSelectedItem("");
        txtAl.setText("");
        btnMasSave.setEnabled(true);
        txtMasNik.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMasBatal;
    private javax.swing.JButton btnMasLog;
    private javax.swing.JButton btnMasSave;
    private javax.swing.JComboBox<String> cbJenis;
    private javax.swing.JComboBox<String> cbJv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAl;
    private javax.swing.JTextField txtMasNama;
    private javax.swing.JTextField txtMasNik;
    // End of variables declaration//GEN-END:variables
}
